spring:
  h2:
    console:
      enable: true
      path: /h2-console

  datasource:
    driver-clsas-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop